apiVersion: v1
kind: Service
metadata:
  name: web-client
spec:
  selector:
    app: web-client
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
        - name: web-client
          image: laskolaskov/ws-web-client:0.0.1
          ports:
            - containerPort: 5000